name = "FjordsSim"
uuid = "0c33e1da-db83-441e-bdcc-232a98675987"
authors = ["limash <yakubov.sha@gmail.com>"]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ClimaOcean = "0376089a-ecfe-4b0e-a64f-9c555d74d754"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
OceanBioME = "a49af516-9db8-4be4-be45-1dad61c5a376"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Oceanostics = "d0ccf422-c8fb-49b5-a76d-74acdde946ac"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Adapt = "4"
CSV = "0.10"
CUDA = "4, 5"
CairoMakie = "0.10, 0.11, 0.12, 0.13"
ClimaOcean = "0.8"
DataFrames = "1"
Downloads = "1.6"
FileIO = "1"
GPUArrays = "9, 10, 11"
Interpolations = "0.14, 0.15"
JLD2 = "0.4, 0.5, 0.6"
NCDatasets = "0.12, 0.13, 0.14"
OceanBioME = "0.1, 0.10, 0.11, 0.12, 0.13, 0.14"
Oceananigans = "0.100.4, 0.100.5"
Oceanostics = "0.1, 0.15, 0.16"
OpenSSL_jll = "3.5.1"
Preferences = "1.5.0"
Scratch = "1"
SeawaterPolynomials = "0.3.5"
julia = "1.10"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
